config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'admin/index', as: 'user_root'

  get 'admin' => 'admin#index'

  resources :blogs

  resources :cart_elements

  resources :order_infos

  resources :orders

  resources :clients

  get 'home/index'

  resources :images

  resources :sales

  resources :products

  get 'products/:id/add_category' => 'products#add_category', as: :add_category
  get 'products/:id/remove_cat' => 'products#remove_cat', as: :remove_cat
  get 'products/:id/add_sale' => 'products#add_sale', as: :add_sale
  get 'products/:id/remove_sale' => 'products#remove_sale', as: :remove_sale
  post 'products/:id/change_show' => 'products#change_show', as: :change_show

  get 'api/products/:id' => 'api#products'
  get 'api/product/:id' => 'api#product'
  get 'api/categories' => 'api#categories'
  get 'api/get_cart' => 'api#get_cart'
  get 'api/blog' => 'api#blog'
  get 'api/my_orders' => 'api#my_orders'
  get 'api/get_order_items' => 'api#get_order_items'

  post 'api/auth' => 'api#authorization'
  post 'api/add_cart' => 'api#add_cart'
  post 'api/add_item' => 'api#add_item'
  post 'api/add_items' => 'api#add_items'
  post 'api/pay_success' => 'api#pay_success'
  post 'api/add_item_count' => 'api#add_item_count'
  post 'api/remove_item_count' => 'api#remove_item_count'
  post 'api/remove_item' => 'api#remove_item'
  post 'api/search' => 'api#search'

  resources :categories

  root 'home#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/cart.rb
class Cart < ActiveRecord::Base

  has_many :user_cart
  has_many :clients, through: :user_cart

  has_many :cart_order
  has_many :orders, through: :cart_order

  has_many :cart_elements

end

app/models/cart_element.rb
class CartElement < ActiveRecord::Base

  belongs_to :cart
  belongs_to :product
  belongs_to :order
end

app/models/cart_order.rb
class CartOrder < ActiveRecord::Base
  belongs_to :order
  belongs_to :cart
end

app/models/category.rb
class Category < ActiveRecord::Base


  require 'RMagick'

  has_attached_file :avatar,
                    :styles => {
                        :thumb => ["100x100", :jpg],
                        :pagesize => ["500x400", :jpg],
                    },
                    :default_style => :pagesize


  attr_accessor :x1, :y1, :width, :height

  def update_attributes(att)

    scaled_img = Magick::ImageList.new(self.avatar.path)
    orig_img = Magick::ImageList.new(self.avatar.path(:original))
    scale = orig_img.columns.to_f / scaled_img.columns

    args = [ att[:x1], att[:y1], att[:width], att[:height] ]
    args = args.collect { |a| a.to_i * scale }

    orig_img.crop!(*args)
    orig_img.write(self.avatar.path(:original))

    self.avatar.reprocess!
    self.save

    super(att)
  end

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  has_many :prod_cats
  has_many :products, through: :prod_cats
end

app/models/client.rb
class Client < ActiveRecord::Base

  belongs_to :cart
  has_many :orders

end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :prod_image
  has_many :products, through: :prod_image

end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :cart_order
  has_many :carts, through: :cart_order

  belongs_to :client

end

app/models/order_info.rb
class OrderInfo < ActiveRecord::Base
end

app/models/prod_cat.rb
class ProdCat < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/prod_iamge.rb
class ProdIamge < ActiveRecord::Base
  belongs_to :product
  belongs_to :image
end

app/models/prod_image.rb
class ProdImage < ActiveRecord::Base
  belongs_to :product
  belongs_to :image
end

app/models/prod_sale.rb
class ProdSale < ActiveRecord::Base
  belongs_to :product
  belongs_to :sale
end

app/models/product.rb
class Product < ActiveRecord::Base

  require 'RMagick'

  has_attached_file :avatar,
                    :styles => {
                        :thumb => ["100x100", :jpg],
                        :pagesize => ["500x400", :jpg],
                    },
                    :default_style => :pagesize


  attr_accessor :x1, :y1, :width, :height

  def update_attributes(att)

    scaled_img = Magick::ImageList.new(self.avatar.path)
    orig_img = Magick::ImageList.new(self.avatar.path(:original))
    scale = orig_img.columns.to_f / scaled_img.columns

    args = [ att[:x1], att[:y1], att[:width], att[:height] ]
    args = args.collect { |a| a.to_i * scale }

    orig_img.crop!(*args)
    orig_img.write(self.avatar.path(:original))

    self.avatar.reprocess!
    self.save

    super(att)
  end

  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  has_many :prod_cats
  has_many :categories, through: :prod_cats
  has_many :prod_sale
  has_many :sales, through: :prod_sale
  has_many :prod_image
  has_many :images, through: :prod_image


end

app/models/sale.rb
class Sale < ActiveRecord::Base
  has_many :prod_sale
  has_many :products, through: :prod_sale
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_cart.rb
class UserCart < ActiveRecord::Base
  belongs_to :client
  belongs_to :cart
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
#  before_action :authenticate_user, only: [:show, :new, :create, :update, :destroy]
  before_filter :authenticate_user!
  skip_before_filter :authenticate_user!, only: [:index]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|

        respond = {:items => @categories}
        format.html { render  hrml: @categories }
        format.json {  }

    end

  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end


  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update_attributes(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :avatar, :x1, :y1, :width, :height)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => "form-horizontal category" , :multipart => true } do |f| %>

  <% if @category.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <%= f.label :avatar, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">

      <%= f.file_field :avatar %>

    </div>
    <%=f.error_span(:avatar) %>
  </div>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                categories_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>


<%= javascript_include_tag 'jquery.min.js' %>
<%= javascript_include_tag 'jquery.Jcrop.js' %>

<%= form_for @category, :html => { :class => "form-horizontal category" , :multipart => true } do |f| %>

    <% if @category.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @category.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
      <%=f.error_span(:name) %>
    </div>



    <script type="text/javascript" language="JavaScript">
        function showCoords( c ) {
            $( '#category_x1' ).val(c.x);
            $( '#category_y1' ).val(c.y);
            $( '#category_width' ).val(c.w);
            $( '#category_height' ).val(c.h);
        }
        $(function(){

            var jcrop_api;

            $('#jcrop_target').Jcrop({
                onChange: showCoords,
                onSelect: showCoords
            },function(){

                var offset = $("#cropimage").offset()

                if ( $("#cropimage").width() >=  $("#cropimage").height() ) {

                    var wd =  $("#cropimage").width()
                    var hg =  $("#cropimage").width() / 2;

                }
                else {
                    var wd =  $("#cropimage").width()
                    var hg =  $("#cropimage").width() / 2;
                }

                jcrop_api = this;
                jcrop_api.setSelect([0,0, wd,hg])

                jcrop_api.setOptions({ allowResize: !!this.checked });
                jcrop_api.focus();

            });

        });
    </script>

    <h1>Editing upload</h1>

    <!-- CROP FORM -->
    <div id='jcrop_target'>
      <%= image_tag @category.avatar.url, :id => 'cropimage' %>
    </div>

    <div id='cropresults'>
      <%= f.label 'x1' %>
      <%= f.text_field 'x1', :size => 6 %>
      <br />
      <%= f.label 'y1' %>
      <%= f.text_field 'y1', :size => 6 %>
      <br />
      <%= f.label 'width' %>
      <%= f.text_field 'width', :size => 6 %>
      <br />
      <%= f.label 'height' %>
      <%= f.text_field 'height', :size => 6 %>
      <br />
    </div> <!-- cropresults -->
    <!-- END CROP FORM -->




    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    categories_path, :class => 'btn btn-default' %>
      </div>
    </div>

<% end %>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Категории" %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:Изображение) %></th>
      <th><%= model_class.human_attribute_name(:Название) %></th>
      <th><%= model_class.human_attribute_name(:Создана) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.id, category_path(category) %></td>
        <td><%=image_tag(category.avatar(:thumb)) %></td>
        <td><%= category.name %></td>
        <td><%=l category.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_category_path(category), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      category_path(category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_category_path,
            :class => 'btn btn-primary' %>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @category.name %></dd>

  <%= image_tag @category.avatar.url %>
  <%= image_tag @category.avatar.url(:medium) %>
  <%= image_tag @category.avatar.url(:thumb) %>
</dl>


<%= link_to t('.back', :default => t("helpers.links.back")),
              categories_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_category_path(@category), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>