config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'admin/index', as: 'user_root'

  get 'admin' => 'admin#index'

  resources :blogs

  resources :cart_elements

  resources :order_infos

  resources :orders

  resources :clients

  get 'home/index'

  resources :images

  resources :sales

  resources :products

  get 'products/:id/add_category' => 'products#add_category', as: :add_category
  get 'products/:id/remove_cat' => 'products#remove_cat', as: :remove_cat
  get 'products/:id/add_sale' => 'products#add_sale', as: :add_sale
  get 'products/:id/remove_sale' => 'products#remove_sale', as: :remove_sale
  post 'products/:id/change_show' => 'products#change_show', as: :change_show

  get 'api/products/:id' => 'api#products'
  get 'api/product/:id' => 'api#product'
  get 'api/categories' => 'api#categories'
  get 'api/get_cart' => 'api#get_cart'
  get 'api/blog' => 'api#blog'
  get 'api/my_orders' => 'api#my_orders'
  get 'api/get_order_items' => 'api#get_order_items'

  post 'api/auth' => 'api#authorization'
  post 'api/add_cart' => 'api#add_cart'
  post 'api/add_item' => 'api#add_item'
  post 'api/add_items' => 'api#add_items'
  post 'api/pay_success' => 'api#pay_success'
  post 'api/add_item_count' => 'api#add_item_count'
  post 'api/remove_item_count' => 'api#remove_item_count'
  post 'api/remove_item' => 'api#remove_item'
  post 'api/search' => 'api#search'

  resources :categories

  root 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base

  require 'RMagick'

  has_attached_file :avatar,
                    :styles => {
                        :thumb => ["100x100", :jpg],
                        :pagesize => ["500x400", :jpg],
                    },
                    :default_style => :pagesize


  attr_accessor :x1, :y1, :width, :height

  def update_attributes(att)

    scaled_img = Magick::ImageList.new(self.avatar.path)
    orig_img = Magick::ImageList.new(self.avatar.path(:original))
    scale = orig_img.columns.to_f / scaled_img.columns

    args = [ att[:x1], att[:y1], att[:width], att[:height] ]
    args = args.collect { |a| a.to_i * scale }

    orig_img.crop!(*args)
    orig_img.write(self.avatar.path(:original))

    self.avatar.reprocess!
    self.save

    super(att)
  end

  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  has_many :prod_cats
  has_many :categories, through: :prod_cats
  has_many :prod_sale
  has_many :sales, through: :prod_sale
  has_many :prod_image
  has_many :images, through: :prod_image


end

app/models/product/product.rb
require 'RMagick'

attr_accessor :x1, :y1, :width, :height

def update_attributes(att)

  scaled_img = Magick::ImageList.new(self.avatar.path)
  orig_img = Magick::ImageList.new(self.avatar.path(:original))
  scale = orig_img.columns.to_f / scaled_img.columns

  args = [ att[:x1], att[:y1], att[:width], att[:height] ]
  args = args.collect { |a| a.to_i * scale }

  orig_img.crop!(*args)
  orig_img.write(self.avatar.path(:original))

  self.avatar.reprocess!
  self.save

  super(att)
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_action :verify_authenticity_token, only: [ :change_shows ]

  # skip_before_filter :authenticate_user!, only: [:index]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show

  @image = Image.new

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end


  def add_category

    if  Product.find(params[:id]).categories.exists?(params[:c_id])
      render :json  => { :name => "error" }
else

      newRel = ProdCat.new
      newRel.product = Product.find(params[:id])
      newRel.category = Category.find(params[:c_id])
      newRel.save
      render :json  => { :name => newRel.category.name }
end



  end

  def remove_cat
    Product.find(params[:id]).categories.delete(params[:c_id])

   render :json  => { :name => Product.find(params[:id]).categories }

  end

  def add_sale

    if  Product.find(params[:id]).sales.exists?(params[:s_id])
      render :json  => { :name => "error" }
else

      newRel = ProdSale.new
      newRel.product = Product.find(params[:id])
      newRel.sale = Sale.find(params[:s_id])
      newRel.save
      render :json  => { :name => newRel.sale.name }
end



  end

  def remove_sale
    Product.find(params[:id]).sales.delete(params[:s_id])

   render :json  => { :name => Product.find(params[:id]).sales }

  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

       if @product.save
        flash[:notice] = 'User was successfully created.'
        if params[:product][:avatar].blank?
          redirect_to(@product)
        else
          puts @product.name
          render :action => 'edit'
        end
      else
        render :action => 'new'
      end
   end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update


    if @product.update_attributes(product_params)
      if params[:product][:avatar].blank?
        flash[:notice] = "Successfully updated user."
        redirect_to @product
      else
        render :action => "edit"
      end
    else
      render :action => 'edit'
    end

  end

  def change_show

    @product = Product.find(params[:id])

    @product.show = params[:show]

    @product.save

    render nil

  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :size, :sizeTable, :color, :description, :price, :sale, :avatar, :show, :brend, :count, :x1, :y1, :width, :height)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => "form-horizontal product" , :multipart => true, :style=>"width: 60%; margin: auto" } do |f| %>

    <% if @product.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @product.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
      <%=f.error_span(:name) %>
    </div>
    <div class="form-group">
      <%= f.label :size, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :size, :class => 'form-control' %>
      </div>
      <%=f.error_span(:size) %>
    </div>
    <div class="form-group">
      <%= f.label :sizeTable, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.select :sizeTable ,  [['Таблица размеров для бюстгальтеров', 1], ['Таблица для спаренных размеров', 2], ['Таблица для одиночных размеров ', 3], ['MТаблица для больших и универсальных размеров ', 4], ['Колготки и чулки', 5]] , {} , { :class => 'form-control' }   %>
      </div>
      <%=f.error_span(:sizeTable) %>
    </div>
    <div class="form-group">
      <%= f.label :show, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.select :show ,  [['Скрыть', 0], ['Показать', 1]] , {} , { :class => 'form-control' }   %>
      </div>
      <%=f.error_span(:sizeTable) %>
    </div>
    <div class="form-group">
      <%= f.label :color, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :color, :class => 'form-control' %>
      </div>
      <%=f.error_span(:color) %>
    </div>
    <div class="form-group">
      <%= f.label :description, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_area :description, :class => 'form-control', :style => "height: 200px" %>
      </div>
      <%=f.error_span(:description) %>
    </div>
    <div class="form-group">
      <%= f.label :price, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :price, :class => 'form-control' %>
      </div>
      <%=f.error_span(:price) %>
    </div>
    <div class="form-group">
      <%= f.label :Количество, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :count, :class => 'form-control' %>
      </div>
      <%=f.error_span(:count) %>
    </div>
    <div class="form-group">
      <%= f.label :sale, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :sale, :class => 'form-control' %>
      </div>
      <%=f.error_span(:sale) %>
    </div>
    <div class="form-group">
      <%= f.label :brend, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :brend, :class => 'form-control' %>
      </div>
      <%=f.error_span(:sale) %>
    </div>
    <div class="form-group">
      <%= f.label :avatar, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.file_field :avatar, :class => 'form-control'  %>
      </div>
      <%=f.error_span(:sale) %>
    </div>

    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    products_path, :class => 'btn btn-default' %>
      </div>
    </div>

<% end %>

app/views/products/crop.html.erb
<% content_for(:head) do %>
    <%= stylesheet_link_tag "jquery.Jcrop" %>
    <%= javascript_include_tag "jquery.Jcrop.min" %>
    <script type="text/javascript" charset="utf-8">
        $(function() {
            $('#cropbox').Jcrop({
                onChange: update_crop,
                onSelect: update_crop,
                setSelect: [0, 0, 500, 500],
                aspectRatio: 1
            });
        });

        function update_crop(coords) {
            var rx = 100/coords.w;
            var ry = 100/coords.h;
            $('#preview').css({
                width: Math.round(rx * <%= @product.avatar_geometry(:normal).width %>) + 'px',
                height: Math.round(ry * <%= @product.avatar_geometry(:normal).height %>) + 'px',
                marginLeft: '-' + Math.round(rx * coords.x) + 'px',
                marginTop: '-' + Math.round(ry * coords.y) + 'px'
            });
            var ratio = <%= @product.avatar_geometry(:original).width %> / <%= @product.avatar_geometry(:normal).width %>;
            $("#crop_x").val(Math.round(coords.x * ratio));
            $("#crop_y").val(Math.round(coords.y * ratio));
            $("#crop_w").val(Math.round(coords.w * ratio));
            $("#crop_h").val(Math.round(coords.h * ratio));
        }
    </script>
<% end %>

<%= image_tag @product.avatar.url(:normal), :id => "cropbox" %>

<h4>Preview:</h4>
<div style="width:100px; height:100px; overflow:hidden">
  <%= image_tag @product.avatar.url(:normal), :id => "preview" %>
</div>

<% form_for @product do |f| %>
    <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
        <%= f.hidden_field attribute, :id => attribute %>
    <% end %>



    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit "Crop", :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    products_path, :class => 'btn btn-default' %>
      </div>
    </div>
    <div id="image_border">
    </div>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>

<%= javascript_include_tag 'jquery.min.js' %>
<%= javascript_include_tag 'jquery.Jcrop.js' %>

<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= form_for @product, :html => { :class => "form-horizontal product" , :multipart => true, :style=>"width: 60%; margin: auto" } do |f| %>

    <% if @product.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @product.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
      <%=f.error_span(:name) %>
    </div>
    <div class="form-group">
      <%= f.label :size, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :size, :class => 'form-control' %>
      </div>
      <%=f.error_span(:size) %>
    </div>
    <div class="form-group">
      <%= f.label :sizeTable, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.select :sizeTable ,  [['Таблица размеров для бюстгальтеров', 1], ['Таблица для спаренных размеров', 2], ['Таблица для одиночных размеров ', 3], ['MТаблица для больших и универсальных размеров ', 4], ['Колготки и чулки', 5]] , {} , { :class => 'form-control' }   %>
      </div>
      <%=f.error_span(:sizeTable) %>
    </div>
    <div class="form-group">
      <%= f.label :show, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.select :show ,  [['Скрыть', 0], ['Показать', 1]] , {} , { :class => 'form-control' }   %>
      </div>
      <%=f.error_span(:sizeTable) %>
    </div>
    <div class="form-group">
      <%= f.label :color, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :color, :class => 'form-control' %>
      </div>
      <%=f.error_span(:color) %>
    </div>
    <div class="form-group">
      <%= f.label :description, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_area :description, :class => 'form-control', :style => "height: 200px" %>
      </div>
      <%=f.error_span(:description) %>
    </div>
    <div class="form-group">
      <%= f.label :price, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :price, :class => 'form-control' %>
      </div>
      <%=f.error_span(:price) %>
    </div>
    <div class="form-group">
      <%= f.label :Количество, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :count, :class => 'form-control' %>
      </div>
      <%=f.error_span(:count) %>
    </div>
    <div class="form-group">
      <%= f.label :sale, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :sale, :class => 'form-control' %>
      </div>
      <%=f.error_span(:sale) %>
    </div>
    <div class="form-group">
      <%= f.label :brend, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :brend, :class => 'form-control' %>
      </div>
      <%=f.error_span(:sale) %>
    </div>
    <div class="form-group">
      <%= f.label :avatar, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.file_field :avatar, :class => 'form-control'  %>
      </div>
      <%=f.error_span(:sale) %>
    </div>




    <script type="text/javascript" language="JavaScript">
        function showCoords( c ) {
            $( '#product_x1' ).val(c.x);
            $( '#product_y1' ).val(c.y);
            $( '#product_width' ).val(c.w);
            $( '#product_height' ).val(c.h);
        }
        $(function(){

            var jcrop_api;

            $('#jcrop_target').Jcrop({
                onChange: showCoords,
                onSelect: showCoords
             },function(){

                var offset = $("#cropimage").offset()

                if ( $("#cropimage").width() <  $("#cropimage").height() ) {

                    var wd =  $("#cropimage").width()
                    var hg =  $("#cropimage").width() * 1.3;

                }
                else {
                    var wd =  $("#cropimage").height() / 1.3
                    var hg =  $("#cropimage").height();
                }

                jcrop_api = this;
                jcrop_api.setSelect([0,0, wd,hg])

                jcrop_api.setOptions({ allowResize: !!this.checked });
                jcrop_api.focus();

            });

        });
    </script>

    <h1>Editing upload</h1>

    <!-- CROP FORM -->
    <div id='jcrop_target'>
      <%= image_tag @product.avatar.url, :id => 'cropimage' %>
    </div>

    <div id='cropresults'>
      <%= f.label 'x1' %>
      <%= f.text_field 'x1', :size => 6 %>
      <br />
      <%= f.label 'y1' %>
      <%= f.text_field 'y1', :size => 6 %>
      <br />
      <%= f.label 'width' %>
      <%= f.text_field 'width', :size => 6 %>
      <br />
      <%= f.label 'height' %>
      <%= f.text_field 'height', :size => 6 %>
      <br />
    </div> <!-- cropresults -->
    <!-- END CROP FORM -->



    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit "Crop", :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    products_path, :class => 'btn btn-default' %>
      </div>
    </div>
    <div id="image_border">
    </div>




<% end %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Продукты" %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:Изображение) %></th>
      <th><%= model_class.human_attribute_name(:Названи) %></th>
      <th><%= model_class.human_attribute_name(:Размер) %></th>
      <th><%= model_class.human_attribute_name(:Таблица_размеров) %></th>
      <th><%= model_class.human_attribute_name(:Цвет) %></th>
      <th><%= model_class.human_attribute_name(:Описание) %></th>
      <th><%= model_class.human_attribute_name(:Цена) %></th>
      <th><%= model_class.human_attribute_name(:Скидка) %></th>
      <th><%= model_class.human_attribute_name(:Количество) %></th>
      <th><%= model_class.human_attribute_name(:Бренд) %></th>
      <th><%= model_class.human_attribute_name(:Показать) %></th>
      <th><%= model_class.human_attribute_name(:Создан) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%=image_tag(product.avatar(:thumb)) %></td>
        <td><%= product.name %></td>
        <td><%= product.size %></td>
        <td><%= product.sizeTable %></td>
        <td><%= product.color %></td>
        <td><%= product.description.truncate(100) %></td>
        <td><%= product.price %></td>
        <td><%= product.sale %></td>
        <td><%= product.count %></td>
        <td><%= product.brend %></td>
        <td><%= form_for(product,
                     remote: true) do |f| %>
            <div class="form-group" style="width: 170px">
              <div class="col-lg-10">
                <%= f.select :show ,  [['Скрыть', 0], ['Показать', 1]] , {} , { :class => 'form-control prod_show' , :id => product.id }  %>
              </div>
              <%=f.error_span(:sizeTable) %>
            </div>
        <% end %>
        </td>
        <td><%=l product.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Добавление категории</h4>
      </div>
      <div class="modal-body">
        <%= collection_select(:prod, :cat_id,  Category.where.not(id: @product.categories), :id, :name, {} , :class =>  'form-control') %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" >Закрыть</button>
        <button type="button" class="btn btn-primary" onclick="addCat(<%= params[:id] %>)">Добавить</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="SaleModal" tabindex="-1" role="dialog" aria-labelledby="SaleModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Добавление акции</h4>
      </div>
      <div class="modal-body">
        <%= collection_select(:prod, :sale_id,  Sale.where.not(id: @product.sales), :id, :name, {} , :class =>  'form-control') %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" >Закрыть</button>
        <button type="button" class="btn btn-primary" onclick="addSale(<%= params[:id] %>)">Добавить</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="ImageModal" tabindex="-1" role="dialog" aria-labelledby="ImageModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Добавление акции</h4>
      </div>
      <%= form_for(@image , :html =>  { :multipart => true }, :remote => true )  do |f| %>



          <div class="form-group">
            <%= f.label :avatar, :class => 'control-label col-lg-2' %>
            <div class="col-lg-10">

              <%= f.file_field :avatar, :class => 'form-control'  %>

            </div>
            <%=f.error_span(:avatar) %>
          </div>


          <input type="hidden" value="<%= params[:id] %>" name="prod_id">
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" >Закрыть</button>

            <%= f.submit 'Добавить' , :class => 'btn btn-primary' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:size) %>:</strong></dt>
  <dd><%= @product.size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sizeTable) %>:</strong></dt>
  <dd><%= @product.sizeTable %></dd>
  <dt><strong><%= model_class.human_attribute_name(:color) %>:</strong></dt>
  <dd><%= @product.color %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sale) %>:</strong></dt>
  <dd><%= @product.sale %></dd>
  <dt><strong><%= model_class.human_attribute_name(:show) %>:</strong></dt>
  <dd><%= @product.show %></dd>
  <dt><strong><%= model_class.human_attribute_name(:brend) %>:</strong></dt>
  <dd><%= @product.brend %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Количество) %>:</strong></dt>
  <dd><%= @product.count %></dd>

  <dd><%= image_tag @product.avatar() , id: "avatar" %></dd>

  <dd style="margin: 10px">
    <h4>Категории:</h4><br><br>

    <ul class="list-group" id="categories">
      <% @product.categories.each do |cat| %>
          <li class="list-group-item" style="width: 200px; float: left" id="cat_<%= cat.id %>">
            <span class=" fa fa-remove " aria-hidden="true" style="float: right;" onclick="removeCat(<%= cat.id %> , <%= params[:id] %>)"></span>
            <%= cat.name %>
          </li>
      <% end %>

    </ul>

  </dd>
  <dd style="margin: 10px">
    <h4>Акции:</h4></h5><br><br>
    <ul class="list-group" id="sales">
      <% @product.sales.each do |sale| %>
          <li class="list-group-item" style="width: 200px; float: left" id="sale_<%= sale.id %>">
            <span class=" fa fa-remove " aria-hidden="true" style="float: right;" onclick="removeSale(<%= sale.id %> , <%= params[:id] %>)"></span>
            <%= sale.name %>
          </li>
      <% end %>

    </ul>
  </dd>


  <dd style="margin: 10px">
<h4>Изображения:</h4><br><br>
    <ul class="list-group" id="images">
      <% @product.images.each do |image| %>
          <li class="list-group-item" style="width: 200px; float: left" id="image_<%= image.id %>">
            <%= link_to t('.destroy', :default => '' ),
                        image_path(image),
                        :remote => true ,
                        :style => "float: right; text-decoration: none; " ,
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => ' fa fa-remove del_image' %>
            <%= image_tag image.avatar(:thumb) %>
          </li>
      <% end %>

    </ul>

  </dd>



  <button type="button" class="btn btn-default navbar-btn" data-toggle="modal" data-target="#myModal">Добавить категорию</button>
  <button type="button" class="btn btn-default navbar-btn" data-toggle="modal" data-target="#SaleModal">Добавить акцию</button>
  <button type="button" class="btn btn-default navbar-btn" data-toggle="modal" data-target="#ImageModal">Добавить изображения</button>



  <%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>


  </div>
</dl>